
@echo off

::set OPTION=-compilerMode viaJavaSource
::set OPTION=-compilerMode directClassFiles
set OPTION=-compilerMode simulaClassLoader

set OPTION=%OPTION% -noConsole
set OPTION=%OPTION% -sport
echo The Options used: %OPTION%
set OPTION=%OPTION% -runtimeUserDir C:\GitHub\SimulaCompiler2\SimulaTestBatch\src\simulaSamples

cd C:\Users\omyhr\Simula\Simula-2.0

java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/SimulaTest.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst01.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst02.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst03.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst04.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst05.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst06.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst07.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst08.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst09.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst10.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst11.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst12.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst13.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst14.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst15.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst16.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst17.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst18.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst19.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst20.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst21.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst22.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst23.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst24.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst25.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst26.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst27.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst28.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst29.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst30a.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst30.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst31.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst32.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst33.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst34.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst35.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst36.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst37.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst38.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst39.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/p40b.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/p40a.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/p40c.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst40.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/p41.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst41.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst42.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst43.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst44.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst45.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst46.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst47.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst48.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst49.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst50.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst51.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst52.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst53.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst54.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst55.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst56.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst57.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst58.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst59.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst60.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst61.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst62.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst63.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst64.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst65.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst66.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst67.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst68.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst69.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst70.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst71.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst72.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst73.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst74.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst75.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst76.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst77.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst78.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst79.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst80.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst81.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst82.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst83.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst84.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst85.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/Separat.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst86.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst87.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst88.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst89.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst90.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst91.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst92.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst93.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst94.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst95.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst96.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst97.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst98.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst99.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst100.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst101.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst102.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst103.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst104.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst105.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst107.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst108.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst109.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst110.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst111.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst112.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst113.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst114.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst115.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst116.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst117.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst118.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/ExternalClass1.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/ExternalClass2.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst119.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst120.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst121.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst122.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst123.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst124.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst125.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst126.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst127.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst128.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/Precompiled129.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst129.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst130.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst131.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst132.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst133.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst134.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst135.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst136.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst137.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst138.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst139.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst140.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst141.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst142.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst143.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/Precompiled144.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst144.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst145.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst146.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst147.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst148.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst149.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst150.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst151.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst152.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst153.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst154.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/Pre155.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst155.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst156.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst157.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst158.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst159.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst160.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst161.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simtst162.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/RT_ErrorTest.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr01.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr02.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/PrecompiledClass.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr03.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/PrecompiledProcedure.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr04.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr05.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr06.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr07.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr08.sim
java -jar simula.jar %OPTION% C:\GitHub\SimulaCompiler2\SimulaTestBatch/src/simulaTestBatch/simerr09.sim

echo The Options used: %OPTION%

pause